import * as DBus from 'dbus-next';
import { EventEmitter } from 'events';

/*
 * Generated by dbus-next interface generator
 */

/**
 * org.bluez.GattCharacteristic1
 */
export class OrgBluezGattCharacteristic1 extends EventEmitter {

    public readonly dbusInterfaceName = 'org.bluez.GattCharacteristic1';
    public dbusObject: DBus.ProxyObject;
    public propertiesDBusInterface: DBus.ClientInterface;
    public thisDBusInterface: DBus.ClientInterface;

    constructor(dbusObject: DBus.ProxyObject) {
        super();
        this.dbusObject = dbusObject;
        this.thisDBusInterface = dbusObject.getInterface('org.bluez.GattCharacteristic1');
        this.propertiesDBusInterface = dbusObject.getInterface('org.freedesktop.DBus.Properties');

        // forward property change events
        this.propertiesDBusInterface.on('PropertiesChanged', (iface: string, changed: any, invalidated: any) => {
            if(iface === this.dbusInterfaceName) {
                this.emit('PropertiesChanged', iface, changed, invalidated);
            }
        });
        // forward all signals
        this.on("newListener", this.thisDBusInterface.on.bind(this.thisDBusInterface));
        this.on("removeListener", this.thisDBusInterface.removeListener.bind(this.thisDBusInterface));
    }

    /***** Properties *****/

    public getProperties(): Promise<{[name: string]: DBus.Variant}> {
        return this.propertiesDBusInterface.GetAll(this.dbusInterfaceName);
    }

    public getProperty(name: string): Promise<DBus.Variant> {
        return this.propertiesDBusInterface.Get(this.dbusInterfaceName, name);
    }

    public setProperty(name: string, value: DBus.Variant): Promise<DBus.Variant> {
        return this.propertiesDBusInterface.Set(this.dbusInterfaceName, name, value);
    }

    //@property({ name: 'UUID', signature: 's', access: ACCESS_READ })
    public UUID(): Promise<string> {
        return this.propertiesDBusInterface.Get(this.dbusInterfaceName, 'UUID');
    }

    //@property({ name: 'Service', signature: 'o', access: ACCESS_READ })
    public Service(): Promise<DBus.ObjectPath> {
        return this.propertiesDBusInterface.Get(this.dbusInterfaceName, 'Service');
    }

    //@property({ name: 'Value', signature: 'ay', access: ACCESS_READ })
    public Value(): Promise<Buffer> {
        return this.propertiesDBusInterface.Get(this.dbusInterfaceName, 'Value');
    }

    //@property({ name: 'Notifying', signature: 'b', access: ACCESS_READ })
    public Notifying(): Promise<boolean> {
        return this.propertiesDBusInterface.Get(this.dbusInterfaceName, 'Notifying');
    }

    //@property({ name: 'Flags', signature: 'as', access: ACCESS_READ })
    public Flags(): Promise<Array<string>> {
        return this.propertiesDBusInterface.Get(this.dbusInterfaceName, 'Flags');
    }

    //@property({ name: 'WriteAcquired', signature: 'b', access: ACCESS_READ })
    public WriteAcquired(): Promise<boolean> {
        return this.propertiesDBusInterface.Get(this.dbusInterfaceName, 'WriteAcquired');
    }

    //@property({ name: 'NotifyAcquired', signature: 'b', access: ACCESS_READ })
    public NotifyAcquired(): Promise<boolean> {
        return this.propertiesDBusInterface.Get(this.dbusInterfaceName, 'NotifyAcquired');
    }


    /***** Methods *****/

    //@method({ name: 'ReadValue', inSignature: 'a{sv}', outSignature: 'ay' })
    public ReadValue(options: {[key: string]: DBus.Variant}): Promise<Buffer> {
        return this.thisDBusInterface.ReadValue(options);
    }

    //@method({ name: 'WriteValue', inSignature: 'aya{sv}', outSignature: '' })
    public WriteValue(value: Buffer, options: {[key: string]: DBus.Variant}): Promise<void> {
        return this.thisDBusInterface.WriteValue(value, options);
    }

    //@method({ name: 'AcquireWrite', inSignature: 'a{sv}', outSignature: 'hq' })
    public AcquireWrite(options: {[key: string]: DBus.Variant}): Promise<any> {
        return this.thisDBusInterface.AcquireWrite(options);
    }

    //@method({ name: 'AcquireNotify', inSignature: 'a{sv}', outSignature: 'hq' })
    public AcquireNotify(options: {[key: string]: DBus.Variant}): Promise<any> {
        return this.thisDBusInterface.AcquireNotify(options);
    }

    //@method({ name: 'StartNotify', inSignature: '', outSignature: '' })
    public StartNotify(): Promise<void> {
        return this.thisDBusInterface.StartNotify();
    }

    //@method({ name: 'StopNotify', inSignature: '', outSignature: '' })
    public StopNotify(): Promise<void> {
        return this.thisDBusInterface.StopNotify();
    }

}
/***** Signals for org.bluez.GattCharacteristic1 *****/
export declare interface OrgBluezGattCharacteristic1 {
    on(evt: "PropertiesChanged", cb: (iface: string, changedProperties: {[key:string]: any}, invalidatedProperties: string[]) => void): this;
    on(event: string, listener: Function): this;
}


