import * as DBus from 'dbus-next';
import { 
    LooselyTypedEmitter, EventListenerSignature,
    wrapDbusVariant, wrapDbusVariantObject, wrapDbusVariantArray, wrapDbusSignature,
    unwrapDbusVariantObject, unwrapDbusVariantArray, unwrapDbusVariant, unwrapDbusVariantAll, unwrapDbusSignature
} from '../utilts';

/*
 * Generated by dbus-next interface generator
 * Template: typescript-class-auto.ts.hbs
 */


/***** Signals for org.bluez.GattCharacteristic1 *****/
interface OrgBluezGattCharacteristic1Events {

    "PropertiesChanged": (iface: string, changedProperties: {[key:string]: any}, invalidatedProperties: string[]) => void;
}
/***** Properties of org.bluez.GattCharacteristic1 *****/
export interface OrgBluezGattCharacteristic1Props {
    UUID: string;
    Service: DBus.ObjectPath;
    Value: Buffer;
    Notifying: boolean;
    Flags: Array<string>;
    WriteAcquired: boolean;
    NotifyAcquired: boolean;
}
/**
 * Service: org.bluez
 * ObjectPath: /org/bluez/hci0/dev_80_E1_26_08_94_85/-/-
 * Interface: org.bluez.GattCharacteristic1
 */
export class OrgBluezGattCharacteristic1<L extends EventListenerSignature<L> = {}> extends LooselyTypedEmitter<OrgBluezGattCharacteristic1Events & L> {
    public static readonly DbusInterfaceName = 'org.bluez.GattCharacteristic1';

    public dbusObject: DBus.ProxyObject;
    public propertiesDBusInterface: DBus.ClientInterface;
    public thisDBusInterface: DBus.ClientInterface;

    public static Connect(bus: DBus.MessageBus, objectPath: string, xml?: string): Promise<OrgBluezGattCharacteristic1> {
        return bus.getProxyObject('org.bluez', objectPath, xml).then((obj) => new OrgBluezGattCharacteristic1(obj));
    }

    constructor(dbusObject: DBus.ProxyObject) {
        super();
        this.dbusObject = dbusObject;
        this.thisDBusInterface = this.dbusObject.getInterface('org.bluez.GattCharacteristic1');
        this.propertiesDBusInterface = this.dbusObject.getInterface('org.freedesktop.DBus.Properties');

        // forward property change events
        const forwardPropertyChange = (iface: string, changed: any, invalidated: any) => {
            if(iface === OrgBluezGattCharacteristic1.DbusInterfaceName) {
                this.emit('PropertiesChanged', iface, unwrapDbusVariantObject(changed), invalidated);
            }
        }

        // forward all signals
        this.on("newListener", (event: string, listener: (...args: any[]) => void) => {
            if(event === "PropertiesChanged" && this.listenerCount('PropertiesChanged') === 0) {
                this.propertiesDBusInterface.addListener('PropertiesChanged', forwardPropertyChange);
            } else {
                this.thisDBusInterface.addListener(event, listener);
            }
        });
        this.on("removeListener", (event: string, listener: (...args: any[]) => void) => {
            if(event === "PropertiesChanged" && this.listenerCount('PropertiesChanged') === 0) {
                this.propertiesDBusInterface.removeListener('PropertiesChanged', forwardPropertyChange);
            } else {
                this.thisDBusInterface.removeListener(event, listener);
            }
        });
    }
    /***** Properties *****/

    public getProperties(): Promise<Partial<OrgBluezGattCharacteristic1Props>> {
        return this.propertiesDBusInterface.GetAll(OrgBluezGattCharacteristic1.DbusInterfaceName).then(unwrapDbusVariantObject);
    }

    public getProperty<T extends keyof OrgBluezGattCharacteristic1Props>(name: T): Promise<OrgBluezGattCharacteristic1Props[T]> {
        return this.propertiesDBusInterface.Get(OrgBluezGattCharacteristic1.DbusInterfaceName, name).then(unwrapDbusVariant);
    }

    public setProperty<T extends keyof OrgBluezGattCharacteristic1Props>(name: T, value: OrgBluezGattCharacteristic1Props[T]): Promise<void> {
        return this.propertiesDBusInterface.Set(OrgBluezGattCharacteristic1.DbusInterfaceName, name, wrapDbusVariant(value));
    }

    //@property({ name: 'UUID', signature: 's', access: ACCESS_READ })
    public UUID(): Promise<string> {
        return this.propertiesDBusInterface.Get(OrgBluezGattCharacteristic1.DbusInterfaceName, 'UUID').then(unwrapDbusVariant);
    }

    //@property({ name: 'Service', signature: 'o', access: ACCESS_READ })
    public Service(): Promise<DBus.ObjectPath> {
        return this.propertiesDBusInterface.Get(OrgBluezGattCharacteristic1.DbusInterfaceName, 'Service').then(unwrapDbusVariant);
    }

    //@property({ name: 'Value', signature: 'ay', access: ACCESS_READ })
    public Value(): Promise<Buffer> {
        return this.propertiesDBusInterface.Get(OrgBluezGattCharacteristic1.DbusInterfaceName, 'Value').then(unwrapDbusVariant);
    }

    //@property({ name: 'Notifying', signature: 'b', access: ACCESS_READ })
    public Notifying(): Promise<boolean> {
        return this.propertiesDBusInterface.Get(OrgBluezGattCharacteristic1.DbusInterfaceName, 'Notifying').then(unwrapDbusVariant);
    }

    //@property({ name: 'Flags', signature: 'as', access: ACCESS_READ })
    public Flags(): Promise<Array<string>> {
        return this.propertiesDBusInterface.Get(OrgBluezGattCharacteristic1.DbusInterfaceName, 'Flags').then(unwrapDbusVariant);
    }

    //@property({ name: 'WriteAcquired', signature: 'b', access: ACCESS_READ })
    public WriteAcquired(): Promise<boolean> {
        return this.propertiesDBusInterface.Get(OrgBluezGattCharacteristic1.DbusInterfaceName, 'WriteAcquired').then(unwrapDbusVariant);
    }

    //@property({ name: 'NotifyAcquired', signature: 'b', access: ACCESS_READ })
    public NotifyAcquired(): Promise<boolean> {
        return this.propertiesDBusInterface.Get(OrgBluezGattCharacteristic1.DbusInterfaceName, 'NotifyAcquired').then(unwrapDbusVariant);
    }

    /***** Methods *****/

    //@method({ name: 'ReadValue', inSignature: 'a{sv}', outSignature: 'ay' })
    public ReadValue(options: {[key: string]: any}, ): Promise<Buffer> {
        return this.thisDBusInterface.ReadValue(wrapDbusSignature(options, "a{sv}"), ).then(unwrapDbusSignature("ay"));
    }

    //@method({ name: 'WriteValue', inSignature: 'aya{sv}', outSignature: '' })
    public WriteValue(value: Buffer, options: {[key: string]: any}): Promise<void> {
        return this.thisDBusInterface.WriteValue(wrapDbusSignature(value, "ay"), wrapDbusSignature(options, "a{sv}"));
    }

    //@method({ name: 'AcquireWrite', inSignature: 'a{sv}', outSignature: 'hq' })
    public AcquireWrite(options: {[key: string]: any}, ): Promise<any> {
        return this.thisDBusInterface.AcquireWrite(wrapDbusSignature(options, "a{sv}"), ).then(unwrapDbusSignature("hq"));
    }

    //@method({ name: 'AcquireNotify', inSignature: 'a{sv}', outSignature: 'hq' })
    public AcquireNotify(options: {[key: string]: any}, ): Promise<any> {
        return this.thisDBusInterface.AcquireNotify(wrapDbusSignature(options, "a{sv}"), ).then(unwrapDbusSignature("hq"));
    }

    //@method({ name: 'StartNotify', inSignature: '', outSignature: '' })
    public StartNotify(): Promise<void> {
        return this.thisDBusInterface.StartNotify();
    }

    //@method({ name: 'StopNotify', inSignature: '', outSignature: '' })
    public StopNotify(): Promise<void> {
        return this.thisDBusInterface.StopNotify();
    }

}
